name: Test

on:
  push:
    branches:
      - main
      - 'dev-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r pyivcmp/requirements.txt
          python -m pip install -r pyivcmp/requirements-dev.txt
      - name: Build library
        run: |
          cmake CMakeLists.txt
          make
      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
          python -m unittest discover tests
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: b0ac32a32f4c12abc822ba5b31882f3f
          filename: ivcmp__${{ env.BRANCH }}.json
          label: Test Coverage
          message: 42
          color: green
          namedLogo: jest
