name: testing

on:
  push:
    branches:
      - main
      - 'dev-**'
      - badge

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set env.BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r pyivcmp/requirements.txt
          python -m pip install -r pyivcmp/requirements-dev.txt
      - name: Build library
        run: |
          cmake CMakeLists.txt
          make
      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
          python -m pytest pyivcmp --cov=pyivcmp
          python -m pytest pyivcmp --cov=pyivcmp --cov-report=xml
          genbadge coverage -i coverage.xml
      - name: Put badge
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_SECRET }}
          gist_id: b0ac32a32f4c12abc822ba5b31882f3f
          gist_file_name: ivcmp-${{ env.BRANCH }}-coverage-badge.svg
          file_path: coverage-badge.svg
